### ISSUE TITLE
Support for TL_BODY

### ISSUE THREAD

**Issue by cboelter** [netzmacht/contao-toolkit#11]
Hi @dmolineus,

short question, do you think it make sense to also support TL_BODY in the https://github.com/netzmacht/contao-toolkit/tree/master/src/View/Assets Functions? If you think, I could provide a pull request.

**Comment by dmolineus** [comment]
Supporting `TL_BODY` would be useful imho. As you can use it not only for assets I would prefer another service for it. I have following interface in my mind:

```php

namespace Netzmacht\Contao\Toolkit\View\HtmlPage;

interface HtmlPage
{
    public function appendToBody(string $html): self;

    public function appendToHeader(string $html): self;
}

```

The advantage for another service I see here, that some shortcuts could be added later on, f.e. for adding meta tags to the header and so on.

**Comment by dmolineus** [comment]
Added with c53966d

**Comment by cboelter** [comment]
@dmolineus very nice! Thanks :-)
