### ISSUE TITLE
Autoregister the Models in Contao

### ISSUE THREAD

**Issue by cboelter** [netzmacht/contao-toolkit#15]
As you know I'm working very often with the toolkit and the repositories. But everytime I register a new repository I forget to register the model in the ```$GLOBALS['TL_MODELS']```.
Maybe it would be nice to register the models automatically if I add a repository for the model.

What do you think about it? Is there a good way to implement that?

**Comment by dmolineus** [comment]
I like the idea. Yes, it's possible. I already doing it for the components (modules/ces). That's how it could be done:

1. Register a hook listener for the `initializeSystemHook` which gets an constructor parameter with a map for the known repositories.
2. A compiler pass get all tagged repositories and overrides the parameter of the listener mentioned above.

Here is the implementation done for the components?

 - https://github.com/netzmacht/contao-toolkit/blob/master/src/Bundle/DependencyInjection/Compiler/ComponentDecoratorPass.php
 - https://github.com/netzmacht/contao-toolkit/blob/master/src/Bundle/DependencyInjection/Listener/RegisterComponentDecoratorsListener.php

Would you mind creating a PR for it? ;-)

**Comment by cboelter** [comment]
Yes I can create a PR for that :-) ... currently working on a few projects using the repositories :-)

**Comment by dmolineus** [comment]
PR got merged
