### ISSUE TITLE
getData()

### ISSUE THREAD

**Issue by Sioweb** [netzmacht/contao-toolkit#18]
Ho!

ich würde gerne mit getData die Daten eines Inhlalt-Elementes ausgeben. Ich finde allerdings keine Möglichkeit die Daten zu bekommen, wenn ein Element mit dem ContentElementDecorator erzeugt wurde.

Übersehe ich hier etwas, evt. ist es auch Absicht dass diese Daten nicht ausgelesen werden können?

LG
Sascha

```php
// type = 'bs_gridStart'
$strClass = ContentElement::findClass($objRow->type);
    
/** @var ContentElement $objElement */
if($strColumn === null) {
    $strColumn = 'main';
}
$objElement = new $strClass($objRow, $strColumn);
$objElement->generate();

// method $objElement->Template->getData() not defined?!
if(empty($objElement->Template)) {
    die('<pre>' . print_r($objElement->component, true)); /** NULL, weil protected */
}
```

**Comment by dmolineus** [comment]
Der `ContentElementDecorator` stellt die von `Contao\ContentElement` definierten Schnittstellen zur Verfügung. Ich halte es grundsätzlich für eine schlechte Idee statt auf die Schnittstelle auf die Internas einer Implementierung zu vertrauen. Sobald ein CE eine angepasste generate() Methode nutzt, die kein Template nutzt, scheitert das Vorhaben.

Wenn du dich schon in de Internas einklinken willst, warum dann nicht über die definierten Hooks von Contao?

```php
$spy = new class() {
    public $data;

    public function onParseTemplate(\Contao\Template $template) : void
    {
        if ($this->data === null && strpos($template->getName(), 'ce_') === 0) {
            $this->data = $template->getData();
        }
    }
};

$GLOBALS['TL_HOOKS']['parseTemplate']['spy-data'] = [$spy, 'onParseTemplate'];

$objElement = new $strClass($objRow, $strColumn);
$objElement->generate();

\var_dump($spy->data);

unset($GLOBALS['TL_HOOKS']['parseTemplate']['spy-data']);
```

**Comment by Sioweb** [comment]
Ho! & Danke.

Für mich war getData die Schnittstelle, danke für den Hook-Hinweis.

LG
Sascha
