### ISSUE TITLE
Callbacks error

### ISSUE THREAD

**Issue by t-me** [netzmacht/contao-toolkit#19]
Hey all,

I have a problem with creating a callback.
I have follewed the information on  [https://contao-developer-toolkit.readthedocs.io/en/develop/dca/callbacks.html](https://contao-developer-toolkit.readthedocs.io/en/develop/dca/callbacks.html).
When i install the packages it shows me this error :

```
17:25:17 ERROR     [console] Error thrown while running command "cache:warmup --env=prod". Message: "Class 'Netzmacht\Contao\Toolkit\Dca\Callback\Callbacks' not found" ["exception" => Error { …},"command" => "cache:warmup --env=prod","message" => "Class 'Netzmacht\Contao\Toolkit\Dca\Callback\Callbacks' not found"]

In SitenzoIsotopeProduct.php line 4:
  Attempted to load class "Callbacks" from namespace "Netzmacht\Contao\Toolkit\Dca\Callback".
  Did you forget a "use" statement for another namespace?
```

You can find my code here [https://github.com/t-me/contao-academy](https://github.com/t-me/contao-academy) **Higly unstable**

Thanks for the help.

**Comment by dmolineus** [comment]
Sorry, this part of the docs are out of date and still refer to the 2.x version of the toolkit.

You may have a look at this real world example how to use the toolkit for dca listeners:

 - The listener: https://github.com/netzmacht/contao-leaflet-maps/blob/master/src/Listener/Dca/MarkerDcaListener.php
 -  Service registration: https://github.com/netzmacht/contao-leaflet-maps/blob/master/src/Bundle/Resources/config/listeners.yml#L60
 - Usage in the dca: https://github.com/netzmacht/contao-leaflet-maps/blob/master/src/Bundle/Resources/contao/dca/tl_leaflet_marker.php#L26

**Comment by t-me** [comment]
@dmolineus Thanks for the feedback.

I think I'm still doing it wrong thou, can you look at my code en tell me where im going wrong?
I'm new to contao 4

My files are :

- The listener [https://github.com/sitenzo/academy-bundle/blob/master/src/Listener/Dca/IsotopeProduct.php](https://github.com/sitenzo/academy-bundle/blob/master/src/Listener/Dca/IsotopeProduct.php)
- Service registration [https://github.com/sitenzo/academy-bundle/blob/master/src/Resources/config/listeners.yml](https://github.com/sitenzo/academy-bundle/blob/master/src/Resources/config/listeners.yml)
- Usage in the dca [https://github.com/sitenzo/academy-bundle/blob/master/src/Resources/contao/dca/tl_iso_product.php](https://github.com/sitenzo/academy-bundle/blob/master/src/Resources/contao/dca/tl_iso_product.php)

Thanks

**Comment by dmolineus** [comment]
I think you don't need this library at all if you're new to Contao. I'm not available for free support. Sorry.

You might want to ask your questions in the [Contao Community](https://community.contao.org) or use the [Contao slack channel](https://join.slack.com/t/contao/shared_invite/enQtNjUzMjY4MDU0ODM3LTc0Nzg5ZWJmZTBlNGFjODhlNjIxNTYxMTYzNWYxYTc0ZDQ4OWVjYmVhNDIwOTBjOWIxZDhkMTE2ZTQyMDMyZjc).
