### ISSUE TITLE
Update auf Contao 4.8

### ISSUE THREAD

**Issue by kehr-solutions** [netzmacht/contao-toolkit#24]
Hi,

habe soeben versucht ein Update auf Contao 4.8 zu machen. Erhalte danach beim Frontend Aufruf folgende Fehlermeldung.

**Template engine "NameVomBundle" is not supported. Has to be toolkit.**

`
Template engine "NameVomBundle" is not supported. Has to be toolkit.
in ToolkitTemplateNameParser.php line 81
at ToolkitTemplateNameParser->guardSupportedEngine('NameVomBundle')in ToolkitTemplateNameParser.php line 34
at ToolkitTemplateNameParser->parse('NameVomBundle:export:index.html.twig')in ToolkitTemplateEngine.php line 140
at ToolkitTemplateEngine->getTemplateReference('NameVomBundle:export:index.html.twig')in ToolkitTemplateEngine.php line 64
at ToolkitTemplateEngine->render('NameVomBundle:export:index.html.twig', array())in ControllerTrait.php line 211
at AbstractController->renderView('NameVomBundle:export:index.html.twig')in ExportController.php line 42
at ExportController->indexAction(object(Request))in HttpKernel.php line 151
at HttpKernel->handleRaw(object(Request), 1)in HttpKernel.php line 68
at HttpKernel->handle(object(Request), 1, true)in Kernel.php line 198
at Kernel->handle(object(Request), 1, true)in SubRequestHandler.php line 85
at SubRequestHandler::handle(object(ContaoKernel), object(Request), 1, true)in HttpCache.php line 478
at HttpCache->forward(object(Request), true, null)in HttpCache.php line 57
at HttpCache->forward(object(Request), true)in HttpCache.php line 450
at HttpCache->fetch(object(Request), true)in ContaoCache.php line 55
at ContaoCache->fetch(object(Request), true)in HttpCache.php line 347
at HttpCache->lookup(object(Request), true)in HttpCache.php line 222
at HttpCache->handle(object(Request), 1, true)in EventDispatchingHttpCache.php line 98
at ContaoCache->handle(object(Request))in index.php line 37
`

**Comment by dmolineus** [comment]
Make sure that the twig template engine stays enabled if you use it. Otherwise the toolkit template engine stays the only the templating engine try to parse every template using the toolkit template engine.

https://github.com/contao/contao/commit/d42ccf43ceb048fb8e4b0bb8d5ad1d0bb45e05f1#diff-eb1e91aff34b45d3a19eab09c406aa06L21-L22
