### ISSUE TITLE
Error in Combination with Contao Bootstrap Grid (Extension)

### ISSUE THREAD

**Issue by vossmedien** [netzmacht/contao-toolkit#29]
After i updated Composer today, i got the following error (from var/logs)

`[2022-01-24T17:03:42.273909+01:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\FatalError: "Compile Error: Declaration of ContaoBootstrap\Grid\Component\ContentElement\GridStopElement::compile() must be compatible with Netzmacht\Contao\Toolkit\Component\AbstractComponent::compile(): void" at /vendor/contao-bootstrap/grid/src/Component/ContentElement/GridStopElement.php line 51 {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Compile Error: Declaration of ContaoBootstrap\\Grid\\Component\\ContentElement\\GridStopElement::compile() must be compatible with Netzmacht\\Contao\\Toolkit\\Component\\AbstractComponent::compile(): void at /vendor/contao-bootstrap/grid/src/Component/ContentElement/GridStopElement.php:51)"} []
`

i downgraded then manually to 3.6.2 and everything was working again.

Dont know on which side the problem but the update of this extension caused it :-)

Thank you and have a nice day!

Christian

**Comment by dmolineus** [comment]
Fix with release 3.7.2
