### ISSUE TITLE
Update von 3.6.2 auf 3.7.2 lässt Leaflet Map im Frontend verschwinden

### ISSUE THREAD

**Issue by saress** [netzmacht/contao-toolkit#30]
Hallo,

ich habe gerade auf einem Staging-Server ein Contao Update gemacht (von C 4.9.22 auf C 4.9.24) und dabei wurden wohl auch einige der Leaflet Maps Dependencies aktualisiert. Nach dem Update wurde die Landkarte im Frontend nicht mehr angezeigt und es war auch keine Spur davon im generierten Sourcecode mehr zu finden.

Ich habe daraufhin kurz die beiden Installationen (Live vs. Staging am selben Server) verglichen und konnte ein paar Abweichungen feststellen. 

![Screenshot-01](https://user-images.githubusercontent.com/1481301/150981751-f37977db-cce2-455d-9c2e-53faf67debce.png)

Ich habe mich dann vorgearbeitet und konnte letztendlich das Problem durch die Version 3.7.2 von contao-toolkit eingrenzen. Wenn ich retour gehe auf die Version 3.6.2 dann funktioniert die Karte im Frontend wieder ganz normal. Eine entsprechende Slack-Diskussion dazu gibt es unter folgendem Link, wobei das ursprüngliche Problem hier ein anderes war:

https://contao.slack.com/archives/CLTUNH78X/p1643095146046800

Beste Grüße
Saress

**Comment by dmolineus** [comment]
Fixed with 96f7ac6303ef82671449a06dff6f894fd6cc7d80 in 3.7.3.

**Comment by saress** [comment]
Herzlichen Dank für den raschen Fix, jetzt funktioniert wieder alles!

Beste Grüße
Saress
