### ISSUE TITLE
PopupWizard some help please

### ISSUE THREAD

**Issue by Misco** [netzmacht/contao-toolkit#38]
Hello,

i am using this toolkit for the first time.
my goal is to have a button for tl_member, it should open a news-element in a popup.
i have a tl_member.php in /app/Resources/contao/dca, it already shows some common fields.

`
$GLOBALS['TL_DCA']['tl_member']['fields']['article'] = [
    'label'                 => ['News-Element', ''],
    'inputType'             => 'select',
    'eval'                  => ['tl_class' => 'w50', 'includeBlankOption' => true],
    'foreignKey'            => 'tl_news.headline',
    'sql'                   => ['type' => 'binary', 'length' => 16, 'default' => ''],
];
$GLOBALS['TL_DCA']['tl_member']['fields']['article']['wizard'][] = [
    Netzmacht\Contao\Toolkit\Dca\Listener\Wizard\PopupWizardListener::class,'onWizardCallback'
];
$GLOBALS['TL_DCA']['tl_member']['fields']['article']['toolkit']['popup_wizard'] = [
    'href'        => 'do=news&amp;id=3&amp;table=tl_news&amp;act=edit',
    'title'       => 'Kategorien',
    'linkPattern' => null,
    'icon'        => 'system/themes/default/images/edit.gif',
    'always'      => false,
];

PaletteManipulator::create()
    ->addLegend('credits_legend', 'personal_legend', PaletteManipulator::POSITION_AFTER)
    ->addField('guthaben,top1,top2,top3,neu,article', 'credits_legend', PaletteManipulator::POSITION_APPEND)
    ->applyToPalette('default', 'tl_member');
`

what is missing?

next step, i wanna find the id with some database call before
each member will have a news-element

thank you for some input, i could not find much about it.

**Comment by Misco** [comment]
The wizard is working, icons are different in my C4.13

`    'icon'        => 'system/themes/flexible/icons/edit.svg',`
the icon is also under the field.


There is one problem:

Ungültiges Token
contao?do=news&table=tl_news&act=edit&id=3&popup=1&nb=1

i think i have to use linkPattern for adding the token, but how?

**Comment by dmolineus** [comment]
Please understand that no support requests can be answered here.
